### ISSUE TITLE
psycopg2/_psycopg.so: undefined symbol: PyUnicodeUCS4_DecodeUTF8

### ISSUE THREAD

**Issue by mam8cc** [jkehler/awslambda-psycopg2#24]
Trying to get up and running with lambda and postgres.  However, running into the below stack trace.  I'm using python 3.6 and SQLAlchemy 1.1.14.

```
/var/task/psycopg2/_psycopg.so: undefined symbol: PyUnicodeUCS4_DecodeUTF8: ImportError
Traceback (most recent call last):
  File "/var/task/hello_world.py", line 9, in handler
    connect_args={'application_name': 'lambda-test'}
  File "/var/task/sqlalchemy/engine/__init__.py", line 391, in create_engine
    return strategy.create(*args, **kwargs)
  File "/var/task/sqlalchemy/engine/strategies.py", line 80, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/var/task/sqlalchemy/dialects/postgresql/psycopg2.py", line 554, in dbapi
    import psycopg2
  File "/var/task/psycopg2/__init__.py", line 50, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: /var/task/psycopg2/_psycopg.so: undefined symbol: PyUnicodeUCS4_DecodeUTF8
```

The artifact I'm deploying to lambda goes something roughly like this:
```
pip install sqlalchemy
zip site-packages
add awslambda-psycopg2 shim to zip
add source code
deploy
```

Some of the zip output:
```
  adding: psycopg2/ (stored 0%)
  adding: psycopg2/__init__.py (deflated 56%)
  adding: psycopg2/_ipaddress.py (deflated 56%)
  adding: psycopg2/_json.py (deflated 65%)
  adding: psycopg2/_psycopg.so (deflated 66%)
  adding: psycopg2/_range.py (deflated 72%)
  adding: psycopg2/errorcodes.py (deflated 65%)
  adding: psycopg2/extensions.py (deflated 59%)
  adding: psycopg2/extras.py (deflated 73%)
  adding: psycopg2/pool.py (deflated 71%)
  adding: psycopg2/psycopg1.py (deflated 60%)
  adding: psycopg2/sql.py (deflated 70%)
  adding: psycopg2/tz.py (deflated 60%)
```

Contents of the .zip:

![image](https://user-images.githubusercontent.com/1774337/32032968-6bb864c8-b9cf-11e7-8315-d446501bc255.png)

Any insight into what I could be missing would be appreciated.

**Comment by mam8cc** [comment]
Cursory googling suggests that the Python you compiled the binaries with differs from what is now running on the lambda hosts.

**Comment by mam8cc** [comment]
Oh, I see there is a `psyopg2-3.6` in the repo.  I thought that was a specific build of a version of `psycopg2`.  Turns out it is for Python 3.6, and using the proper distribution worked.

Thanks for the work!
